version: '3.9'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${TYPEORM_USERNAME}
      POSTGRES_PASSWORD: ${TYPEORM_PASSWORD}
      POSTGRES_DB: ${TYPEORM_DATABASE}
      POSTGRES_HOST: ${TYPEORM_HOST}
      POSTGRES_PORT: ${TYPEORM_PORT}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
